# Generated by Django 4.1.2 on 2022-10-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('hour', models.IntegerField()),
                ('market_demand', models.IntegerField()),
                ('ontario_demand', models.IntegerField()),
                ('market_peak_day', models.BooleanField()),
                ('ontario_peak_day', models.BooleanField()),
                ('market_peak_month', models.BooleanField()),
                ('ontario_peak_month', models.BooleanField()),
            ],
        ),
    ]
